### PR TITLE
Make RawDecoder and RawEncoder Send

### PR DESCRIPTION
**Pull request by klutzy**

### CODE REVIEW

**Comment by lifthrasiir** [comment]
Looks good to me, but you would need a test (probably a `thread::spawn` call with captured `RawEncoder`s etc).

**Comment by lifthrasiir** [comment]
Thank you!

**Comment by hsivonen** [comment]
What's the use case for sending decoders or encoders (as opposed to the encoding objects) across threads?

**Comment by lifthrasiir** [comment]
@hsivonen In general making a type `Send` expands the possible usages of that type, and I see no issue on making encoders and decoders `Send`. (In fact, all current encoders and decoders are already `Send`able and non-`Send`able types are very unlikely to appear.) Rust does not make potentially `Send`able types implement `Send` by default, but only because it is a part of API stability guarantee.

**Pull request merged**
